export const CONFIG = {
  UNISWAP_V2_CONTRACT_ADDRESS: "YOUR_UNISWAP_V2_CONTRACT_ADDRESS",
  MOCKERC20_ADDRESS: "YOUR_MOCKERC20_ADDRESS",
  MOCK_USDC_ADDRESS: "YOUR_MOCK_USDC_ADDRESS",
  INFURA_PROJECT_ID: "YOUR_INFURA_PROJECT_ID",
};
