name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

permissions:
  contents: write  # 允许 Actions 写入仓库内容

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # 使用最新版本

      - name: Setup Node.js
        uses: actions/setup-node@v3  # 使用最新版本
        with:
          node-version: '18.x'  # 设置为兼容版本

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build
        run: yarn build
        working-directory: ./frontend

      - name: List directory (for debugging)
        run: ls -alh ./frontend/out  # 确保 out 目录存在并包含构建文件

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/out
          publish_branch: gh-pages  # 指定发布到 gh-pages 分支
